// Optional, dependency-free packaging for Sites. The portfolio itself is static.
import { readFile, mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = fileURLToPath(new URL("../", import.meta.url));
const files = {
    "/": ["index.html", "text/html; charset=utf-8"],
    "/styles.css": ["styles.css", "text/css; charset=utf-8"],
    "/app.js": ["app.js", "text/javascript; charset=utf-8"],
    "/img/BilledeAfmig1.JPG": ["img/BilledeAfmig1.JPG", "image/jpeg"],
    "/public/og.png": ["public/og.png", "image/png"],
    ...Object.fromEntries(["github", "linkedin", "youtube"].map((name) => [
        `/assets/icons/${name}.svg`, [`assets/icons/${name}.svg`, "image/svg+xml"]
    ]))
};

const assets = {};
for (const [url, [file, type]] of Object.entries(files)) {
    assets[url] = { type, body: (await readFile(path.join(root, file))).toString("base64") };
}

const worker = `// Generated by scripts/build.mjs. Edit the original static files instead.
const assets = ${JSON.stringify(assets)};
export default {
    async fetch(request) {
        if (request.method !== "GET" && request.method !== "HEAD") {
            return new Response("Method not allowed", { status: 405, headers: { Allow: "GET, HEAD" } });
        }
        const pathname = new URL(request.url).pathname;
        const asset = assets[pathname === "/index.html" ? "/" : pathname];
        if (!asset) return new Response("Not found", { status: 404 });
        const headers = {
            "Content-Type": asset.type,
            "Cache-Control": "public, max-age=300",
            "X-Content-Type-Options": "nosniff",
            "Referrer-Policy": "strict-origin-when-cross-origin"
        };
        const body = request.method === "HEAD" ? null : Uint8Array.from(atob(asset.body), (c) => c.charCodeAt(0));
        return new Response(body, { headers });
    }
};
`;
await mkdir(path.join(root, "dist/server"), { recursive: true });
await writeFile(path.join(root, "dist/server/index.js"), worker);
console.log(`Packaged ${Object.keys(assets).length} static resources for Sites.`);
